/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Administrateur;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import service.AdministrateurService;
import util.Session;

/**
 *
 * @author asus
 */
public class Connexion extends javax.swing.JFrame {

    AdministrateurService administrateurService = new AdministrateurService();

    /**
     * Creates new form Connexion
     */
    public Connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logtxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        cnxbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(658, 369));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 100, 83, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 150, 83, 30);

        logtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logtxtActionPerformed(evt);
            }
        });
        jPanel1.add(logtxt);
        logtxt.setBounds(520, 100, 128, 30);
        jPanel1.add(pwdtxt);
        pwdtxt.setBounds(520, 150, 128, 30);

        cnxbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        cnxbtn.setText("Se Connecter");
        cnxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnxbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cnxbtn);
        cnxbtn.setBounds(460, 190, 160, 28);

        jLabel3.setFont(new java.awt.Font("Forte", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Connexion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 0, 231, 58);

        imageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yassine\\Documents\\NetBeansProjects\\CabinetMedical\\src\\icons\\13059700_10206492439005872_139178645_n.jpg")); // NOI18N
        jPanel1.add(imageLabel);
        imageLabel.setBounds(0, -60, 400, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logtxtActionPerformed

    private Administrateur getParams() {
        Administrateur myAdministrateur = new Administrateur();
        myAdministrateur.setId(logtxt.getText());
        myAdministrateur.setPasword(pwdtxt.getText());
        return myAdministrateur;
    }

    private void cnxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnxbtnActionPerformed
        // TODO add your handling code here:
        try {
            Administrateur myAdministrateur = administrateurService.seConnecter(getParams());
            if (myAdministrateur == null) {
                JOptionPane.showMessageDialog(null, "PROBLEME DE CONNEXION", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                Session.updateAttribute(myAdministrateur, "administrateur");
                this.setVisible(false);
                new Accueil().setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cnxbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cnxbtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logtxt;
    private javax.swing.JTextField pwdtxt;
    // End of variables declaration//GEN-END:variables
}
